baseURL = 'https://0xpoe.dev/'
buildDrafts = false
buildExpired = false
buildFuture = false
copyright = '© 2025 Dongpo'
enableEmoji = true
enableInlineShortcodes = true
enableRobotsTXT = true
languageCode = 'en-us'
mainSections = ['posts']
pygmentsUseClasses = true
theme = 'PaperMod'
title = 'Dongpo'


[params]
ShowAllPagesInArchive = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowPageNums = true
ShowPostNavLinks = true
ShowReadingTime = true
ShowRssButtonInSectionTermList = true
ShowShareButtons = false
ShowToc = true
author = "Dongpo Liu"
comments = true
defaultTheme = "auto"
description = "Dongpo's personal blog"
displayFullLangName = true
env = "production"


[params.profileMode]
enabled = true
imageHeight = 120
imageTitle = "Dongpo"
imageUrl = "https://avatars.githubusercontent.com/u/29879298?v=4"
imageWidth = 120
subtitle = "👋 My name is Dongpo Liu and I’m a passionate software engineer who specializes in distributed systems and dev tools."
title = "Dongpo"

[params.editPost]
Text = "Suggest Changes"
URL = "https://github.com/0xPoe/blog/tree/master/content"
appendFilePath = true


[outputs]
home = ["HTML", "RSS", "JSON"]

[languages.en]
languageName = "English"
weight = 1

[[languages.en.menu.main]]
name = "Posts"
url = "posts/"
weight = 1

[[languages.en.menu.main]]
name = "Presentations"
url = "presentations/"
weight = 2

[[languages.en.menu.main]]
name = "About"
url = "about"
weight = 3

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 4

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 5


[[params.socialIcons]]
name = "github"
title = "View Source on Github"
url = "https://github.com/0xPoe"

[[params.socialIcons]]
name = "YouTube"
title = "YouTube"
url = "https://www.youtube.com/@poe1024"

[[params.socialIcons]]
name = "LinkedIn"
title = "LinkedIn"
url = "https://www.linkedin.com/in/poe-liu/"

[[params.socialIcons]]
name = "Email"
title = "Email"
url = "mailto:poe.liu@pm.me"

[markup.goldmark.renderer]
unsafe = true

[analytics.google]
SiteVerificationTag = "G-6MJ0XT6MNX"
